baseurl = "https://natefinch.com"
languageCode = "en-us"
title = "natefinch.com"
theme = "hyde"
copyright = "Nate Finch"

[Author]
	name = "Nate Finch"

[Permalinks]
	blog = "/:year/:month/:filename/"
[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "RPG Discussion by<br>Nate Finch"
	twitter = "https://twitter.com/natethefinch"
	github = "https://github.com/natefinch"
	gplus = "https://plus.google.com/+NateFinch"
	disqus = "natefinch"
	mainImage = "/moose.svg"

